vimperator/vimperator-labs

common/locale/en-US/hints.xml

Small typo in the en-US version of the hints help page. The help text on a couple of the commands doesn't correspond to the actual command.

fix minor typos in hints.xml

---

common/content/hints.js
common/locale/en-US/options.xml

A disabled input element is unusable and un-clickable. There's no point
to highlight it.
Fixes #126 (Vimperator mark hint under disabled input fields)

Ignore disabled input elements in hinttags

---

common/content/editor.js

When entering textarea mode, move cursor back one character. This is
like exiting insert mode and going back to normal mode in vim.
Make 'f' and 't' be closer to vim. 'f' goes to right before the
character and 't' being one character before that.
Fix #140.

Make TEXTAREA mode more vim-like.

---

common/content/events.js

In onKeyUpOrDown, we check to see whether we should ignore a particular
key or not. One of the checks is whether an input element is focused.
'inInputElemFocused' checks whether the focused element is an instance
of Input or TextArea or Object or Embed. However, contentEditable divs
should be included in the check because some websites like facebook use
content editable elements instead of other input elements for better
styling.
Fixes #90.

ContentEditable elements are InputElements

---

common/content/browser.js
common/content/commandline.js
common/content/events.js
common/content/liberator.js
common/content/marks.js
common/content/quickmarks.js
common/content/sanitizer.js
common/content/services.js
common/locale/en-US/options.xml
common/modules/storage.jsm
vimperator/NEWS

In non-private mode commands and searches are stored in global
'history-command' and 'history-search' stores respectively.
Since Firefox 20 the private browsing mode is on per window basis.
To support command and search history in per-window private mode:
* save command and search entries in a new
- 'history-command-private' or
- 'history-search-private'
store.
* all opened private windows share these stores
* when the last private window is closed or Firefox itself is closed clear these two private stores.

Fix command history and search history in 'per-window private mode'

---

common/content/browser.js

Hi,
it seems `PlacesUtils.history.setCharsetForURI` has been replaced with `PlacesUtils.setCharsetForURI` ( see: https://bugzilla.mozilla.org/show_bug.cgi?id=880922#c18 ).
I couldn't use `set encoding=` for a while with the error `TypeError: PlacesUtils.history.setCharsetForURI is not a function` and confirmed this change fixed it.
I left the `PlacesUtils.history.setCharsetForURI` for people who uses older versions of Firefox (though I don't know when the change was made... :(

Fix `set encoding=` functionality

---

common/components/protocols.js

Fixes #139.
This is an issue because on line 258, we declare `url` with a `let`, but we also use `url` in 261, but we don't declare it there and if we use `let` there we get issues. So, I just moved the let out of the switch.

Dont redeclare or use let vars improperly

---

common/content/editor.js

example)
body message on muttator's compose window

fix: broken textarea mode when document.designMode is "on"

---

common/content/editor.js

This function is mapped to <S-Insert> and seems to mimic the default
behavior (pasting whatever is in the clipboard). However, it is also the
root of issue #166. I can't think of a reason why it should exist. It
might allow the use of <S-Insert> on Mac OS X, but I don't think
vimperator is the place for that. Also, there's cmd_paste already.

remove pasteClipboard function

---

muttator/content/mail.js

Hi,
A manifestation of this problem is the following: suppose you have two accounts configured, and you selected "unified folders view" (view menu/folders/unified), then for example, you will have a unified inbox root folder, and then two inbox childs folders. Now, if you are in the unified folder, thinks like j/k will not work.
This simple fix just retrieves the folder of the row and uses its db.

fix selectMessage for unify folders

---

common/content/hints.js
common/locale/en-US/hints.xml
vimperator/NEWS

Implement an extended hint mode for yanking anchor URLs of appropriate elements (namely, those that have either an id or name attribute). This is useful for pointing people to a specific part of the page, for instance sections of a Wikipedia article. I chose ;n (aNchor) because ;a and ;A were already taken.

Implement yank anchor URL hint mode.

---

common/content/editor.js

When you edit a text area externally and the editor ends and the text area is updated it never triggers an 'input' event. That is because it is set via `textBox.value = val` instead of user input.
Many sites/apps rely on the 'input' event being triggered to manage their internal store. Notably [TiddlyWiki][1] and [StackOverflow][2]. This forced the user to then further manipulate the content after editing to force the browser to dispatch these events. 
Adding a programmatic 'input' event will prevent this extra user interaction (which with could potentially cause a lose of data in some apps) and trigger JavaScript event handlers appropriately.
[1]: http://tiddlywiki.com/
[2]: http://stackoverflow.com/

Dispatches an input event when editing externally

---

muttator/content/mail.js

This was causing muttator not to work with Thunderbird 36 anymore. Can anyone confirm that this actually fixes the problem #187?

Make muttator work with Thunderbird 36

---

common/skin/liberator.css

Tree Style Tab coveres the floatbox, so you cannot see URL suggestions.

fixed covered .liberator-floatbox

---

muttator/content/mail.js

When composing a mail in Thunderbird, by default, the default identity of the folder/account you're currently viewing is used. When using Muttator, no identity is set, and the default identity is used, which is not always convenient if you're using multiple accounts/identities.
I changed this to use the default identity of the current folder or account, like the default behaviour of Thunderbird.

Better choice of identitty when composing mail

---

common/content/events.js
vimperator/NEWS

`-except` option in ignorekeys are support in `onKeyPress`, but does not support in `onKeyUpOrDown`.
Reproduce methods
---------
1. `:nmap l <C-n>`
2. `:ignorekeys add -except l,<C-n> github.com`
3. Open https://github.com/vimperator/vimperator-labs
4. Press `l`. worked correctly
5. Open https://github.com/vimperator/vimperator-labs/blob/master/.gitignore
6. Press `l`. popup jump window in github and doesn't worked correctly

Stop propagation for keyboard event if that key are contained in -except option on :ignorekeys

---

common/content/tabs.js

Currently it is possible to execute a tab spawn bomb by the simple command(if at least one tab exists):
```
:tabdo tabduplicate
```
This pull request avoids this.

Avoid tab spawn bomb

---

common/content/buffer.js

Replaces the error with a more descriptive one when attempting to scroll on a page that hasn't fully loaded and properly handle it

Fix Node is null when scrolling on loading pages

---

common/content/events.js

Ignore (next) mode currently sends an Escape keypress to the browser, but doesn't leave Ignore (next) mode as it should.

Fix Esc in Ignore mode

---

common/skin/liberator.css

A z-index of 5000 is not enough for some sites.  For example, the menubar at wikia.com sets the z-index to something around 5 million, which obscures the hints.
I verified that `2147483647 = 2^31-1`  is the maximum z-index supported by Firefox. See https://github.com/vimperator/vimperator-labs/issues/255

changed z-index to max allowed by firefox

---

common/skin/liberator.css

This PR replaces the deprecated `png` SSL icons with the new `svg` ones.

Fix #301: Update SSL icons in status line.

---

common/content/commandline.js

Proposal for Issue #26 
This code hides the bottom-bar when in fullscreen mode (youtube, <f11>), and shows the vimperator bar when mode is not 1 (NORMAL)

added autohide for fullscreen mode for Issue #26

---

muttator/content/mail.js

Toggling HTML display mode (hotkey 'x') and header display mode
(hotkey 'h') were broken, because gPrefBranch variable is
undefined with recent Thunderbirds.
Fixes issue #329.

Fixes toggling of HTML display mode and header display mode with hotkeys

---

common/content/statusline.js
common/skin/liberator.css

From Firefox 42, gIdentityHandler methods are changed. So ssl popup was
not working. Fixed this for Firefox 42 and higher, and added more icons
for ssl states and tooltip.

Fix statusline ssl icon is not working

---

common/content/buffer.js
common/locale/en-US/options.xml

If showstatuslinks is set other than 0, there is redundancy of link
previews. So provides an option to hide the bottom-left corner link
preview.

Added showstatuslinks values hiding link preview

---

common/content/commandline.js

* Non-visible, or deleted search engines are not exposed
in the UI, and as far as the user is concerned they do
not exist.
* The default search engines (or other deleted ones) may
still be stored (search.json etc).
* With this in mind, suggestengines should respect the
ability to delete (hide) engines, and only show/use
visible search engines.
While minor. it does add some confusion when working with `suggestengines`. Especially so, if one or more of your search engines does not include support for search suggestions. It can be difficult to tell if the search engines are stored in multiple places, out of sync or whatever.

Suggestengines only using visible search engines

---

common/locale/en-US/marks.xml
common/locale/ja/marks.xml

* The separator used in documentation is "hardcoded", as such
it can be a bit confusing when it does not work with ", "
in the event the urlseparator option is changed.
* One example: #362

Explain QuickMark groups using urlseparator

---

common/content/events.js
common/content/tabs.js
common/locale/en-US/options.xml
vimperator/NEWS

Allows you to stop keypresses being passed to webpages when you are outside of Insert/Passthrough modes. Fixes #286.

Add option for controlling passthrough to webpages

---

vimperator/content/tabgroup.js
vimperator/locale/en-US/tabs.xml

since i've discovered `:panorama` command, i can't stop using it all the time.  this PL brings missing rename feature.
here some cool remappings from my .vimparatorrc:
```viml
" firefox panorama (groups of tabs)
noremap <M-e> :panorama<Space>
inoremap <M-e> <Esc>:panorama<Space>
noremap <Silent> <M-S-e> :panorama<Space>switch<Space>
inoremap <Silent> <M-S-e> <Esc>:panorama<Space>switch<Space>
```
maybe it would be good idea to add them by default.  note that with `<M-S-e>` remapped, it's still possible to bring firefox's native panorama using `'IGNORE'` mode (pressing `i`).

added :panorama rename subcommand

---

vimperator/content/tabgroup.js

Currently, Vimperator checks for the existence of TabView when first run. My Tab Groups add-on reimplements the tab groups functionality that will be removed in Firefox 45. However it is a restartless add-on, so its functionality can be enabled and disabled immediately without restarting the browser.
In addition, the add-on also makes it possible to (de)initialize just the tabView frame on demand as well (mostly for compatibility with other add-ons).
This pull request addresses both issues. Note that it does not make any sort of pretty print saying "Oops, you've tried to run a panorama command when no panorama exists.". If the add-on and the native Firefox panorama don't exist it will just fail, which is expected anyway.
Note that this still won't work correctly with the currently …

Compatibility with Tab Groups add-on

---

common/content/commands.js

The semantics of `const` has been changed in Firefox 44.
https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/
This patch allows user-defined sub-commands in Firefix 44+.
```js
commands.addUserCommand(['mycommand'], 'My command', function() {}, {
subCommands: [
new commands.Command(['sub'], 'My sub-command', function() { doSomething(); }),
],
});
```

Expose Command constructor

---

common/content/statusline.js

Value of ContentSeparator might change during runtime and it was loaded
from an undefined variable.

Fix #394: ContentSeparator lost after hiding statusbar

---

common/content/statusline.js

setVisibility.contentSeparator is already set.
And setting contentSeparator in toggle_off() makes trouble in manual toggle on/off.

No need to set contentSeparator variable

---

common/content/buffer.js
common/content/commandline.js
common/content/commands.js

This fixes some of AMO's validator's warnings. A bunch we probably can't do anything about easily because they're inherently how the class system is made and how autocommands are made while others are just the validator being silly because it sees "mouseover" and thinks we're listening to it and not handling it correctly.

Fix some validator warnings

---

common/content/hints.js

The issue seems like a z-index issue.
I confirmed hints was fixed on `startpage`.
before fix: http://i.imgur.com/LYYLcdb.png
after fix: http://i.imgur.com/MJpYP8O.png

Fix broken hints in FF44 #388

---

common/skin/liberator.css

`Normal` highlight should control background color of MOW, so I removed implemented background-color of MOW.

Fix #280 CSS transparent is not working on MOW

---

common/content/commandline.js
common/content/finder.js

Fixes #401:
- Don't find immediately on every key pressed while typing complex words (IME compositing).
- Don't show the findbar when searching through the command line and there are no matches.

Findbar fixes

---

common/content/buffer.js
common/content/tabs.js
vimperator/content/tabgroup.js

This essentially just null-checks TabView at every point it should be needed:
- all tabgroups command should no-op if it doesn't exist;
- other non-groups-related commands should just skip their groups bits entirely.
This is just the quickest fix to get it working in Firefox 45, porting all of this into a Vimperator plugin as suggested in #367 is still a possibility, but I don't have that knowledge so I won't be doing that one. ;)

Quick fixes for TabView removal from Firefox

---

common/content/events.js
common/content/modes.js
common/content/statusline.js

Please see this as a DRAFT only (or improve it or merge it if you're happy).
The previous implementation with various state variables was somehow confusing. I tried another approach with modes and events (still via a single interface method `setVisibility(request)`).
There are three modes:
1. `AUTO`: This shows or hides the statusline depending on the fullscreen state.
2. `ON`: Here the statusline is always visible, even in fullscreen.
3. `OFF`: The statusline is hidden, only the commandline is shown after typing a colon.
Several events can happen:
1. `FULLSCREEN`: Whenever the fullscreen state changes.
2. `TOGGLE`: Cycles through all three modes. Currently there's no indicator, so it's not easy with three modes instead of two.
3. `SHOW` and `HIDE`: These are emitted when entering or …

Fix #394: Use modes instead of states

---

common/content/finder.js

As discussed in #426. I also threw in a little cleanup commit to remove a few lines that I noticed are no longer relevant or necessary.

Fix not remembering last searched for value after switching tabs

---

common/content/finder.js

Fixes for https://github.com/vimperator/vimperator-labs/issues/426#issuecomment-190651015 - we were initializing the findbar only when typing in the cmdline, it completely neglected to do this in all other find actions.
And a couple of other things I noticed while working on it:
- it would still show only a substring of the typed query sometimes in the failed search notification in the cmdline, because the findbar keeps track of failed searches (somewhat) and doesn't actually run a search that we can listen to for results to show this notification;
- pressing "n" would still show the findbar on failed searches, since the cursor isn't actually in the cmdline in this case which is what it was checking for before.

Find fixes

---

common/content/buffer.js
common/content/events.js
common/content/liberator.xul
common/content/statusline.js
common/locale/en-US/options.xml
common/locale/ja/options.xml
muttator/content/compose/liberator.xul

Inspired by Pentadactyl which already has this option, this adds the webpage's zoom level to the statusline, e.g. (110%). It can be set with `set status=zoomlevel`.
Enjoy.

Add zoomlevel status option

---

common/content/liberator.js
muttator/locale/en-US/autocommands.xml
vimperator/NEWS
vimperator/content/config.js
vimperator/contrib/vim/syntax/vimperator.vim
vimperator/locale/en-US/autocommands.xml
vimperator/locale/ja/autocommands.xml

Useful for handling interdependencies between plugins without relying on
io.readDirectory()s sorting.

Add PluginsLoadPost autocommand

---

muttator/content/config.js

This unbreaks Muttator on Thunderbird 45 for me. The same workaround is
already committed for Vimperator:
https://github.com/vimperator/vimperator-labs/issues/289#issuecomment-158372213

Unbreak Muttator on Thunderbird 45 (var/const scoping for Config module)

---

common/content/completion.js

Several features relying on completion lists would stop
working or not start at all when hitting this code path.
Fixes #456 as far as I can tell.

Fix a TypeError triggered in completion.js (#456)

---

common/content/base.js
common/content/io.js
common/content/preferences.xul
common/content/util.js

This makes vimperator work with firefox 47 again.
I'm not sure what the implications for older firefox but it probably would work as far back as 40, if not longer.

Don't use Application anymore. FUEL is removed

---

common/content/history.js

This seems to be not necessary and it is causing issues particularly in
firefox 47, there query is a "XPCWrappedNative_NoHelper" and we can't
modify it which is what this loop tries to do.
Wrapping it in a try/catch does fix the issue as well but removing it
altogether seems to also fix it and seems that there are no adverse
effects.
Can someone give this a shot on various some versions of firefox?

Remove unnecessary Iterator loop in history.get

---

vimperator/content/tabgroup.js

I'll be releasing a new version of Tab Groups soon. Most of Vimperator's code should still work though, as I've implemented a series of shims for compatibility with other add-ons like this. I just noted down where the code is using those shims, for reference if/when this is ever rewritten as a vim plugin (even though I have no plans to remove those shims from the add-on).
Two things without shims:
- getPageBounds was moved to UI. But instead of re-referencing it, I just removed that bit since it was irrelevant; getPageBounds always returned a top-left of 0-0, and this was overriding width-height, so getting the actual page bounds was just useless for creating a group.
- no more getActiveOrphanTab method, because there are no more orphan tabs ;)

fixes and notes for Tab Groups 2

---

common/content/help.css

it's safe to remove the element name from the selector, both reducing the size of the CSS as well as improving the selector performance (doesn't have to match the element anymore).

help.css: Disallow overqualified elements

---

common/content/help.css
common/skin/liberator.css
vimperator/skin/about.css

The value of 0 works without specifying units in all situations where numbers with length units or percentages are allowed. There is no difference between 0px, 0em, 0%, or any other zero-value. The units aren't important because the value is still zero. CSS allows you to omit the length units for zero values and still remain valid CSS.
It's recommended to remove units for all zero length values because these units aren't being used by the browser and therefore can be safely removed to save bytes.

Disallow units for zero values

---

common/content/commandline.js

Do not append empty completion preview.

Fix #259: Command prompt selection sometimes cleared

---

common/content/sanitizer.js

as from firefox 46, canClearItem is removed from sanitizer. This PR will check ff version before calling clearItem!

use saniztizer based on app platform version, #556

---

common/content/editor.js

Do not delete the text after the cursor/selection. Fix #560.

fix Shift+Insert paste on Linux

---

common/content/buffer.js
common/locale/en-US/buffer.xml
common/locale/en-US/options.xml
common/locale/ja/buffer.xml
common/locale/ja/index.xml
common/locale/ja/options.xml
muttator/contrib/vim/syntax/muttator.vim

For backward compatibility, 'previouspattern' remains valid.
The reason for this change: "prev" is the standard LINK TYPE, while
"previous" is an often supported (but incorrect) synonym. Therefore,
followDocumentRelationship("prev") is preferred.
Reference:
https://www.w3.org/TR/html4/types.html#type-links
https://www.w3.org/TR/html5/links.html#sequential-link-types
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types

Change option 'previouspattern' to 'prevpattern'.

---

common/content/browser.js
common/content/commandline.js
common/content/commands.js
common/content/tabs.js
vimperator/content/config.js

This allows finding all commands regardless of which command name
was used. E.g. :js <Up> matches on :js, :javas and :javascript.
We special case :open/:tabopen/:winopen, which which are treated the
same. Allowing e.g. :open retrieve URLs that were previously used with
:tabopen.

Canonicalize commandline history during matching

---

common/content/buffer.js
common/locale/en-US/options.xml
common/locale/ja/options.xml

Issue taken from real life: on a page that has both `preview` and `previous` button, `preview` has been winning rendering <kbd>[[</kbd> pretty useless.

Fix [[ following "preview" button

---

common/locale/en-US/options.xml

@maxauthority commented:
> […] However, that feature certainly requires an entry in the help file […]

Add help for statuslinevisibility

---

vimperator/NEWS
vimperator/content/config.js
vimperator/locale/en-US/options.xml

This exposes the NewTabURL API to the user and also provides a fallback
for older versions of Firefox via the browser.newtab.url preference.

Fix #619: Override newtab URL

---

common/content/events.js
common/content/hints.js

This PR includes a few fixes on issues that I noticed or were reported by others related to links hinting (`;o`) as well as a simple refactor to move hints concerns to `hints.js` and avoid useless repetition.
A lot of problems were caused by '0' being both the initial state of hints and a valid part of two or more digits hints (when `hintchars` is numeric that is). The problem with fullscreen appears to come from a delay on the chrome being accessible in that mode... The rest is moving stuff around.
I didn't have time to test all possible cases, hence the long delay on submitting this PR, but since there was some action on a related issue, I'll just go ahead and take feedback from the community.

Fixes and refactor in hints module

---

common/content/statusline.js
common/locale/en-US/options.xml
common/locale/ja/options.xml

Add the SSL icon by default to the statusline for security reasons.
If `gui` is set to `none`, there is now a way to quickly check the
certificate, which is important for users to prevent them from being
harmed.

statusline: add ssl by default (fixes #644)

---

common/Makefile

On BSD flavours of `sed`, the argument to `-i` is non-optional. If no explicit empty string argument is provided, the next token is consumed as the backup filename suffix and subsequent command-line tokens are mis-interpreted.
20cbcd7 "fixes" #648 by correcting a presumed typo that surfaced the problem. This allows `make xpi` to complete on BSD, albeit with a behaviour of `sed -i` inconsistent with GNU and likely not what is intended.
d36b6b4 fixes the underlying issue by supplying the filename suffix for `sed -i` explicitly.

Fix #648: make xpi doesn't work

---

common/content/util.js

a nsITransferable must be initialized before use, otherwise firefox crashes due to a failed assertion.
This fixes issue vimperator/vimperator-labs#660.

nsITransferable must be initialized before use. Fixes vimperator/vimperator-labs#660

---

common/content/bookmarks.js
common/content/history.js

Fixes #654.
I'm not 100% certain that I'm handling URIs vs URLs strictly correctly here.
It appears to fix the problem for me - with this fix, the interface is (mostly) responsive while typing (pauses for at most 1 sec, usually the first time after loading FF, and certainly not up to 5 or more secs like previously), and the results are correctly just the relevant historical quick searches for the keyword URL.
Please review and adjust as necessary.

Remove uriIsPrefix (no longer supported)

---

common/content/base.js
common/content/bookmarks.js
common/content/buffer.js
common/content/commandline.js
common/content/commands.js
common/content/completion.js
common/content/events.js
common/content/hints.js
common/content/io.js
common/content/javascript.js
common/content/liberator.js
common/content/marks.js
common/content/options.js
common/content/tabs.js
common/content/util.js
muttator/content/mail.js
vimperator/NEWS

This PR makes to fix #568 loading the tabs module (see also [the candidate](https://github.com/ma8ma/vimperator-labs/pull/1)).
* Replace legacy generator with ES2015 generator for almost places.
* Replace non-standard Array comprehension with Array methods in muttator/content/mail.js.
Several legacy generators still keep because they have been handled by legacy iterators.
* iter() in common/content/base.js
* callbacks of addPageInfoSection() in common/content/buffer.js
* evaluateXPath() in common/content/util.js
* range() in common/content/util.js
* itervalues() in common/content/util.js
* iteritems() in common/content/util.js

Fix #568: loading the tabs module failed

---

common/content/sanitizer.js

This PR fixes #666, which was caused by the removal of the `canClear` from items in sanitize.js (See Firefox [#1211849](https://bugzilla.mozilla.org/show_bug.cgi?id=1211849))
This PR has been tested on the current Firefox ESR version. It causes no new errors or issues in terms of functionality.
The issues seen in #208 are also fixed with this PR, though it would appear that some issues in the bug report were fixed prior.

Fix #666: Remove deprecated canClear function

---

README.md
vimperator/NEWS

This PR fixes #690, see [here](https://github.com/ma8ma/vimperator-labs/blob/create-readme.md/README.md) for looks.
README.md for people who would like to hack vimperator, it shows the
latest change and the method of building own version. Note that
contributor is required to edit the What's New topic.
Note: Issues or Pull requests numbers don't automatically make links to
the repository, but just leave it as it is because reduce contributor's
burden.

Fix #690: Create README.md

---

vimperator/install.rdf

The Vimperator "Preferences" button on the Firefox Add-ons page now
opens the options help page in a new tab.
I changed the `optionsURL` to the "options" help page and changed the
`optionsType` to `3`, which means:
> Opens optionsURL in a new tab (if the application supports that), or a
> dialog box
See here for documentation:
https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#optionsType
Before, the button did not do anything.
Fixes #574 
If you want me to remove the "Preferences" button completely instead, that would be easily possible. Just let me know.

"Preferences" button now opens options help page

---

common/content/hints.js

When following a unique hint, the `_validHints` array is cleared, thus
the second call of `_processHints` triggers a `beep()` after
following a hint.

Fix #718: Do not call `_processHints` after following a unique hint.

---

common/content/statusline.js

I use a different method to indicate SSL status. The element of
"#connection-icon" is the icon for ssl, so I copied its style to
ssl field of statusline.
In case of InsecureLoginForms, connection-icon is updated after page
load, so ssl field has to be updated on InsecureLoginFormsStateChange.
I have tested this on FF51, but not on FF50.

Fix #677: SSL indicator broken in FF51

---

common/content/browser.js
vimperator/NEWS

As explained in #319, the current urlseparator `",\s+"` is too common in URLs and search strings to be a sensible default separator.
* When copying and pasting some content to look it up with some search engine (for instance a title or an address):
`:open google gödel, escher, bach`
`:open duckduckgo 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA` 
* A comma followed by spaces is also legitimate in a URL! For instance if you put some JSON as a GET parameter in a URL.
`:open http://refine.codefork.com/reconcile/viaf?query={"query": "Scott Aaronson", "type": "/people/person"}`
Therefore I propose to disable this option by default and let users enable it with their preferred separator.
@tot-to, @maxauthority do you support this PR?

Disable urlseparator by default, for #319

---

common/content/statusline.js

With `/(#[a-zA-Z-]+)(-white|-black)?/`, `$1` matches the whole name of
an anchor. For example, `$1` matches '#normal-icon-white' for string
'#normal-icon-white'. The intention is to match '#normal-icon'.

Fix: RegEx in #717 incorrectly matches in some cases

---

CONTRIBUTING.md

I completely removed the section "Development installation". The
proposed way of linking the git repository directly did not work for me
at all.
If you know how to make the direct linking to the git-repo work,
please tell me and I will update the PR again.
I added a section about Firefox Auror/Development to:
- disable e10s
- allow installation of unsigned XPIs

Updated CONTRIBUTING guidelines

---

common/content/liberator.js

With FF55 no new windows could be opened with `:winopen`.
nsISupportsArray was deprecated a long time ago and finally removed in
Firefox 55 (see https://bugzilla.mozilla.org/show_bug.cgi?id=792209).
This should be backwards compatible, but was only tested against FF55.

Remove usage of nsISupportsArray

---

README.md

- Remove statement related to ESR. As of this edit, ESR is now at 74.0.1 and should no longer support XUL-based add-ons.
- Capitalized one instance of "Waterfox" for consistent branding
- Possibly related to [#796](https://github.com/vimperator/vimperator-labs/issues/796)

Update README.md (re: #796)
