vimperator/vimperator-labs

vimperator/locale/ja/intro.xml

Sync Japanese locale with en-US commit dd0c8866e171b2baa591dfbcb152c19c5dd44a4e
Fixes issue #217

Update Japanese locale messages in sync with en-US

---

common/content/hints.js

Ignore visibility and display style for area tags

---

common/content/base.js
common/content/bookmarks.js
common/content/buffer.js
common/content/commandline.js
common/content/events.js
common/content/io.js
common/content/liberator.js
common/content/liberator.xul
common/content/mappings.js
common/content/modes.js
common/content/options.js
common/content/style.js
common/content/template.js
common/content/util.js
common/skin/liberator.css
vimperator/install.rdf

This is still a WIP.
Fixes #231

WIP: Various changes to fix latest aurora/nightly

---

common/content/tabs.js
vimperator/NEWS

When browser.tabs.closeWindowWithLastTab is set to true, make tabs.remove close it

Obey browser.tabs.closeWindowWithLastTab

---

common/content/commands.js

This is just a consistency commit.

Change comments to reflect actual function name

---

common/content/mappings.js

Fix :unmap in vimperator

---

common/content/browser.js
common/locale/en-US/browsing.xml
vimperator/NEWS

Ref #262.
Adds command ```gr``` to toggle Reader View.

Toggle reader view with gr

---

common/content/tabs.js

This fixes tabnumbers styles to support Firefox 41.

fix #274: tabnumbers style issues in FF41

---

common/locale/en-US/options.xml

Seems that things went a bit too fast :-)

Remove misplaced 't', fixes #312.

---

common/content/hints.js

Adds the "Home row (Dvorak)" and "Smart order (Dvorak)" hintchars
options for setting completion.

Add dvorak-friendly hintchars

---

common/content/commandline.js
common/content/events.js
common/content/modes.js
common/content/statusline.js
vimperator/NEWS

Sorry. I closed #337 because "follow hint" did not work in google search pages if statusline was hidden. That seems not my problem. pizzood's code shows the same behavior.
So I again pull request.
From #337:
I mended my old code for #26 a bit. This replaces pizzood's code and provides users a possibility to change the statusline's visibility.

My suggestion for statusline visibility issue #26 (again)

---

common/content/finder.js

- Removed old and unnecessary bits, from before the findbar was per-tab.
- Updated bits to reflect the current async nature of the findbar; please read the note I added at the top about how difficult it would be to implement the TODOs in there. In short, Vimperator would need to create its whole new system, which would make it incompatible with pretty much anything findbar-related out there, and would be hell to maintain.
- Changed the behavior considerably: where before searches through the findbar and through the commandline would be independent, they are now pretty much the same since Vimperator now acts as more of a mediator between the user input in the commandline and the actual findbar.
- Easiest case to visualize is this: find in the commandline "a", then open findbar and find "b" …

Closes #370 use findbar to find through the command line

---

common/content/buffer.js

One my plugins breaks due to Buffer being undefined.

Expose Buffer constructor (see #387).

---

common/content/buffer.js

Fix scrolling

---

common/content/liberator.js
common/content/util.js

See more #422.
I rewrote the patch. and more better than previous patch(#423).
Please review.

Expose useful variable(userContext, NS, etc...) to Global-scope.

---

common/content/buffer.js
common/content/commands.js

Related 3d9c4a9.
Please review.

Fix: this(chrome-window) to modules.

---

muttator/locale/en-US/tutorial.xml
vimperator/locale/en-US/tutorial.xml

clarification  and... ✨ neutrality ✨

revise tutorial

---

common/content/editor.js

Used by e.g. Gmail compose window for formatted text.

Make :iabbr work in contenteditable text boxes

---

common/content/abbreviations.js
common/content/autocommands.js
common/content/base.js
common/content/bookmarks.js
common/content/buffer.js
common/content/commands.js
common/content/completion.js
common/content/editor.js
common/content/events.js
common/content/hints.js
common/content/io.js
common/content/javascript.js
common/content/liberator.js
common/content/mappings.js
common/content/marks.js
common/content/modes.js
common/content/options.js
common/content/quickmarks.js
common/content/sanitizer.js
common/content/services.js
common/content/statusline.js
common/content/style.js
common/content/util.js
common/modules/template-tag.js
vimperator/content/config.js
vimperator/install.rdf

Thanks @reepush, I ended up making the couple of changes to get this in tonight.

Comprehensions review

---

common/content/style.js

https://github.com/vimperator/vimperator-labs/issues/498

Fix "hightlight" typo (#498)

---

muttator/install.rdf

Signed-off-by: Emiapwil (Gao Kai) <emiapwil@gmail.com>

Make muttator work with Thunderbird 45

---

common/content/services.js

Fix issue #590:  Smart Completions not work on Fx49 

---

common/locale/en-US/gui.xml
common/locale/ja/gui.xml
muttator/content/config.js
muttator/locale/en-US/gui.xml
vimperator/content/config.js
vimperator/locale/en-US/gui.xml
vimperator/locale/ja/gui.xml

The only thing missing is jp i10n. I added the new trings in english though - hope that fits your bill.

Fix alphabetic ordering and add :dialog certmgr and connectionprefs

---

common/content/completion.js
common/content/services.js

eg: about:config, about:addons etc. The code was copied from pentadactyl.

add auto completion for about urls

---

common/content/editor.js

Please consider this pull request. It's purely a cosmetic change that removes trailing whitespace. Thanks for developing Vimperator, I hope to contribute more in the future.

delete trailing whitespace

---

common/content/bookmarks.js

Fixes #508 - makes :jumps work again

---

common/content/buffer.js
common/content/commandline.js
common/content/completion.js
common/content/editor.js
common/content/events.js
common/content/hints.js
common/content/io.js
common/content/javascript.js
common/content/liberator.js
common/content/liberator.xul
common/content/options.js
common/content/tabs.js
common/content/template.js
common/javascript.vim

Fixed some misspellings in common directory.

Fix misspelled words

---

common/content/finder.js
vimperator/NEWS

Fix #676: search highlighting on fx51

---

muttator/content/config.js
vimperator/content/config.js

replace openDialog by openURL for connectionprefs dialog

---

common/content/statusline.js

As per the comments in issue #752 this should fix the issue.

Fix #752 (muttator): Use config.browser instead of gBrowser

---

README.md

doc: List alternatives

---

README.md

Added Vim Vixen (Issue #811) and updated the status of Tridactyl, which now has
working beta versions on AMO. Also, wanted to thank the Vimperator developers
for all their hard work over the years.

Updated README.md vimperator alternatives
